on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

name: CI

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install NPM packages
        run: npm install
      - name: Build extension
        run: npm run build
      #- name: Run frontend (React) test cases
      #  run: npm run test
      - name: Run backend test cases
        run: npm run test-backend
      - name: Lint
        run: npm run lint